# Generated by Django 3.2.18 on 2023-05-04 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230503_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
    ]
