# Generated by Django 3.2.18 on 2023-05-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='datecompleted',
        ),
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='month',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
