# Generated by Django 3.2.18 on 2023-05-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20230503_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finish_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='init_time',
            field=models.TimeField(null=True),
        ),
    ]
