# Generated by Django 3.2.18 on 2023-05-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_finish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.IntegerField(choices=[(1, 'Meeting'), (2, 'Visit to a client'), (3, 'Quotation elaboration'), (4, 'Engineering work'), (5, 'Other')], null=True),
        ),
    ]
