# Generated by Django 3.2.18 on 2023-05-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
        migrations.AddField(
            model_name='task',
            name='durationH',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='durationm',
            field=models.IntegerField(null=True),
        ),
    ]
