# Generated by Django 3.2.18 on 2023-05-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_task_datecompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='datecompleted',
        ),
    ]
